### ISSUE TITLE
Cannot read property 'normalModuleFactory' of undefined

### ISSUE THREAD

**Issue by infodevart** [wildpeaks/package-three-webpack-plugin#14] opened 2018-06-27 17:15 UTC
Hey, I'm trying to add this plugin to a project built on"create-react-app" [after ejecting], but I'm getting this error "Cannot read property 'normalModuleFactory' of undefined"

**Comment by cecilemuller** [comment] 2018-06-28 11:54
You can refer to [this project](https://github.com/wildpeaks/threejs-typescript-examples) for an example using the plugin.

create-react-app comes with a heavy list of loaders and plugins that are out of scope of this package, and at the moment I cannot reproduce this normalModuleFactory error.


However, I see from the long "examples as modules" thread in three.js that you were looking to import `CanvasRenderer` which is one of the [files that define multiple classes](https://github.com/wildpeaks/package-three-webpack-plugin/issues/11) (whereas most files only define one class with the same name as the file, and even within, there are quite a few styles of IIFE as well, I even had to resort to parsing the AST to detect what file defines what additional classes because they use so many variants) which is something I'm working on for the next release.

**Comment by infodevart** [comment] 2018-06-28 15:48
Hi @cecilemuller Thank you really for this nice plugin, Yes I was looking to import `CanvasRenderer` I need to add this [example](https://threejs.org/examples/?q=wav#canvas_particles_waves) as a top section of a landing page. I found then that the `CanvasRenderer` is [deprecated](https://threejs.org/docs/#examples/renderers/CanvasRenderer) so I'm trying to remake the example without it. now I'm getting the problem with `SpriteCanvasMaterial` don't have same properties as `SpriteMaterial`. That's another problem.
Anyway, thanks again for this plugin hope you will keep the nice work.

**Comment by cecilemuller** [comment] 2018-06-29 14:30
Alright, then I'll close the issue, thanks 😃 

And good choice with the wave example, that will look great in a page header.

**Closed by cecilemuller** 2018-06-29 14:30 UTC
